"""Make creator_id nullable in lists table

Revision ID: 460ec7ecb821
Revises: 79639179d3dc
Create Date: 2025-12-01 14:43:02.011529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '460ec7ecb821'
down_revision = '79639179d3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_parent_id')

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=postgresql.UUID(),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_brand_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_brand_id', ['brand_id'], unique=False)

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=postgresql.UUID(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('ix_categories_parent_id', ['parent_id'], unique=False)

    # ### end Alembic commands ###
