"""make product_id nullable in conversions

Revision ID: 74122d65c9ab
Revises: 460ec7ecb821
Create Date: 2026-02-08 10:19:02.913130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74122d65c9ab'
down_revision = '460ec7ecb821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
