"""Add price column to product_links

Revision ID: 7ef7028c4678
Revises: 7db21d792ee9
Create Date: 2025-10-28 22:40:36.982778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef7028c4678'
down_revision = '7db21d792ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_links', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
