"""Add retailer_id column to products table

Revision ID: c2e7c08839f0
Revises: e110c5a8065a
Create Date: 2025-11-02 13:51:00.734539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e7c08839f0'
down_revision = 'e110c5a8065a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retailer_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'retailers', ['retailer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('retailer_id')

    # ### end Alembic commands ###
