"""Add conversion lifecycle tracking and payout_type to payouts

Revision ID: f1a2b3c4d5e6
Revises: c2e7c08839f0
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'c2e7c08839f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add fields to conversions table
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchaser_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.add_column(sa.Column('creator_payout_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cashback_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_conversions_purchaser_id', 'users', ['purchaser_id'], ['id'])
        batch_op.create_index('ix_conversions_status', ['status'], unique=False)
    
    # Add payout_type to payouts table
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_type', sa.String(length=20), nullable=False, server_default='creator'))
        batch_op.create_index('ix_payouts_payout_type', ['payout_type'], unique=False)
        batch_op.create_index('ix_payouts_user_id', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove fields from conversions table
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_index('ix_conversions_status')
        batch_op.drop_constraint('fk_conversions_purchaser_id', type_='foreignkey')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('status')
        batch_op.drop_column('cashback_percentage')
        batch_op.drop_column('creator_payout_percentage')
        batch_op.drop_column('purchaser_id')
    
    # Remove payout_type from payouts table
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index('ix_payouts_user_id')
        batch_op.drop_index('ix_payouts_payout_type')
        batch_op.drop_column('payout_type')
    
    # ### end Alembic commands ###
